.TH MQTT_INSPECTOR 1 "February 2026" "bildstod 0.1.0"
.SH NAME
bildstod \- Visual schedule and picture support tool
.SH SYNOPSIS
.B bildstod
.SH DESCRIPTION
.B bildstod
is a GTK4 application for LVisual schedule and picture support tool.
.SH OPTIONS
None currently supported.
.SH AUTHOR
Daniel Nylander <daniel@danielnylander.se>
.SH SEE ALSO
.BR gtk4 (7)
